local t = {
	[0] = "IllIIllIII",
	[1] = "a",
	[2] = "IllIIllIlI",
	[3] = "A",
	[4] = "lllIIllIII",
	[5] = "b",
	[7] = "llIIIllIlI",
	[8] = "B",
	[9] = "IllIIllIll",
	[10] = "c",
	[11] = "IIIIIIIIII",
	[12] = "C",
	[13] = "llllllllll",
	[14] = "d",
	[15] = "lIIIIIIIII",
	[16] = "D",
	[17] = "lllllIIIll",
	[18] = "e",
	[19] = "lllllIIIlL",
	[20] = "E",
	[21] = "LllllIIIll",
	[22] = "f",
	[23] = "llllLLLiii",
	[24] = "F",
	[25] = "IlliiLLLII",
	[26] = "g",
	[27] = "https",
	[28] = "G",
	[29] = "request",
	[30] = "h",
	[31] = "json",
	[32] = "H",
}

return t
